CREATE TABLE article_tags (
    article_id BIGINT NOT NULL,
    tags VARCHAR(255)
);
CREATE TABLE articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255) NOT NULL,
    content VARCHAR(255) NOT NULL,
    author_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_articles PRIMARY KEY (id)
);
CREATE TABLE authors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_authors PRIMARY KEY (id)
);
CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255) NOT NULL,
    content VARCHAR(255) NOT NULL,
    timing TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    capacity INTEGER NOT NULL,
    status VARCHAR(255) NOT NULL,
    author_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_events PRIMARY KEY (id)
);
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    roles VARCHAR(255)
);
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(25) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    city VARCHAR(255),
    street VARCHAR(255),
    number VARCHAR(255),
    apartment VARCHAR(255),
    zip VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);
ALTER TABLE authors
ADD CONSTRAINT uc_author_user_id UNIQUE (user_id);
CREATE INDEX idx_article_title ON articles(title);
CREATE INDEX idx_author_username ON authors(username);
CREATE INDEX idx_event_timing ON events(timing);
CREATE INDEX idx_event_title ON events(title);
ALTER TABLE articles
ADD CONSTRAINT FK_ARTICLES_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES authors (id);
CREATE INDEX idx_article_author_id ON articles(author_id);
ALTER TABLE authors
ADD CONSTRAINT FK_AUTHORS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE events
ADD CONSTRAINT FK_EVENTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES authors (id);
ALTER TABLE article_tags
ADD CONSTRAINT fk_article_tags_on_article FOREIGN KEY (article_id) REFERENCES articles (id);
ALTER TABLE user_roles
ADD CONSTRAINT fk_user_roles_on_user FOREIGN KEY (user_id) REFERENCES users (id);
